import "./globals.css";

export const metadata = {
  title: "Web tutorial",
  description: "Generated by Sarah",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          <a href="/read/1" />
          WEB
        </h1>
        <ol>
          <li>
            <a href="/read/1" />
            html
          </li>
          <li>
            <a href="/read/1" />
            css
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <a href="/create">Create</a>
          </li>
          <li>
            <a href="/update/1">Update</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
