export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children} RootLayout</body>
    </html>
  );
}

// 하위 폴더에 layout.tsx를 생성하여 중첩된 레이아웃을 구성할 수 있음 (상쇄하는게 아니라, 중첩되는거 !)
// <Layout>
//   <AboutUsLayout>
//     <SalesLayout>
//        <Sales/>
//     </SalesLayout>
//    </AboutUsLayout>
// </Layout>
